image: maven:3.8-openjdk-18

stages:
  - build
  - test
  - deploy

cache:
  paths:
    - .m2/repository/

build:
  stage: build
  script:
    - echo "Compilando o projeto..."
    - mvn clean package
    - ls -la target/
  artifacts:
    paths:
      - target/
    expire_in: 1 hour

test:
  stage: test
  script:
    - echo "Executando testes..."
    - mvn test
  artifacts:
    when: always
    paths:
      - target/surefire-reports/
    expire_in: 1 hour

deploy:
  stage: deploy
  script:
    - mkdir -p ~/.ssh
    - echo "$id_rsa_gitlab" > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - ssh-keyscan -H $EC2_HOST >> ~/.ssh/known_hosts
    - ls -la target/  # Verifica se o arquivo está presente
    - scp -i ~/.ssh/id_rsa target/your-app.jar ec2-user@$EC2_HOST:/home/ec2-user/
    - ssh -i ~/.ssh/id_rsa ec2-user@$EC2_HOST "java -jar /home/ec2-user/your-app.jar"
  environment:
    name: production
    url: http://your-production-url.com
  only:
    - main
