image: openjdk:22-jdk

stages:
  - build
  - test
  - deploy

before_script:
  - apt-get update && apt-get install -y maven  # Instala Maven antes de executar os scripts

cache:
  paths:
    - .m2/repository/

build:
  stage: build
  script:
    - echo "Compilando o projeto..."
    - mvn clean package  # Compila o projeto e empacota
  artifacts:
    paths:
      - target/  # Armazena os artefatos de build, como JARs ou WARs
    expire_in: 1 hour  # Configura os artefatos para expirar em 1 hora

test:
  stage: test
  script:
    - echo "Executando testes..."
    - mvn test  # Executa os testes unitários
  artifacts:
    when: always
    paths:
      - target/surefire-reports/  # Guarda os relatórios de teste
    expire_in: 1 hour  # Configura os artefatos para expirar em 1 hora

deploy:
  stage: deploy
  script:
    - echo "Realizando o deployment da aplicação..."
    - mvn deploy -DskipTests  # Realiza o deployment usando Maven
  environment:
    name: production  # Define o ambiente de deploy como produção
    url: http://your-production-url.com  # URL onde a aplicação estará acessível após o deploy
  only:
    - main  # Especifica que este job deve ser executado apenas na branch 'main'
