image: openjdk:22-jdk

stages:
  - build
  - test
  - deploy

before_script:
  # Atualiza o índice de pacotes e instala o Maven usando apk, comum em distros como Alpine Linux.
  - apk update && apk add maven

cache:
  paths:
    - .m2/repository/

build:
  stage: build
  script:
    - echo "Compilando o projeto..."
    - mvn clean package
  artifacts:
    paths:
      - target/

test:
  stage: test
  script:
    - echo "Executando testes..."
    - mvn test
  artifacts:
    paths:
      - target/surefire-reports/

deploy:
  stage: deploy
  script:
    - echo "Realizando o deployment da aplicação..."
    - mvn deploy -DskipTests
  environment:
    name: production
    url: http://your-production-url.com
  only:
    - main
