version: '3.1'
services:
  db-bet-postgres:
    image: postgres
    container_name: bet-database
    environment:
      POSTGRES_ROOT_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: bet-database
    ports:
      - "5432:5432"
    volumes:
      - /var/lib/postgres/betapi

volumes:
  bet-database:
